//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// Regenerate: make generate

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ─── PLCDevice ───────────────────────────────────────────────────────────────

func (in *PLCDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PLCDevice) DeepCopy() *PLCDevice {
	if in == nil {
		return nil
	}
	out := new(PLCDevice)
	in.DeepCopyInto(out)
	return out
}

func (in *PLCDevice) DeepCopyInto(out *PLCDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PLCDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PLCDeviceList) DeepCopy() *PLCDeviceList {
	if in == nil {
		return nil
	}
	out := new(PLCDeviceList)
	in.DeepCopyInto(out)
	return out
}

func (in *PLCDeviceList) DeepCopyInto(out *PLCDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PLCDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PLCDeviceSpec) DeepCopyInto(out *PLCDeviceSpec) {
	*out = *in
	if in.DriverRef != nil {
		in, out := &in.DriverRef, &out.DriverRef
		*out = new(DriverRef)
		**out = **in
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
}

func (in *PLCDeviceStatus) DeepCopyInto(out *PLCDeviceStatus) {
	*out = *in
	if in.LastConnected != nil {
		in, out := &in.LastConnected, &out.LastConnected
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DriverRef) DeepCopyInto(out *DriverRef) { *out = *in }
func (in *DriverRef) DeepCopy() *DriverRef {
	if in == nil {
		return nil
	}
	out := new(DriverRef)
	*out = *in
	return out
}

// ─── Tag ─────────────────────────────────────────────────────────────────────

func (in *Tag) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TagList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TagList) DeepCopy() *TagList {
	if in == nil {
		return nil
	}
	out := new(TagList)
	in.DeepCopyInto(out)
	return out
}

func (in *TagList) DeepCopyInto(out *TagList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *TagSpec) DeepCopyInto(out *TagSpec) { *out = *in }

func (in *TagStatus) DeepCopyInto(out *TagStatus) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// ─── Setpoint ────────────────────────────────────────────────────────────────

func (in *Setpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *Setpoint) DeepCopy() *Setpoint {
	if in == nil {
		return nil
	}
	out := new(Setpoint)
	in.DeepCopyInto(out)
	return out
}

func (in *Setpoint) DeepCopyInto(out *Setpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *SetpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SetpointList) DeepCopy() *SetpointList {
	if in == nil {
		return nil
	}
	out := new(SetpointList)
	in.DeepCopyInto(out)
	return out
}

func (in *SetpointList) DeepCopyInto(out *SetpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Setpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SetpointSpec) DeepCopyInto(out *SetpointSpec) { *out = *in }

func (in *SetpointStatus) DeepCopyInto(out *SetpointStatus) {
	*out = *in
	if in.LastApplied != nil {
		in, out := &in.LastApplied, &out.LastApplied
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// ─── AlarmPolicy ─────────────────────────────────────────────────────────────

func (in *AlarmPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AlarmPolicy) DeepCopy() *AlarmPolicy {
	if in == nil {
		return nil
	}
	out := new(AlarmPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *AlarmPolicy) DeepCopyInto(out *AlarmPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AlarmPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AlarmPolicyList) DeepCopy() *AlarmPolicyList {
	if in == nil {
		return nil
	}
	out := new(AlarmPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *AlarmPolicyList) DeepCopyInto(out *AlarmPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AlarmPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AlarmPolicySpec) DeepCopyInto(out *AlarmPolicySpec) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]AlarmCondition, len(*in))
		copy(*out, *in)
	}
}

func (in *AlarmPolicyStatus) DeepCopyInto(out *AlarmPolicyStatus) {
	*out = *in
	if in.LastTriggered != nil {
		in, out := &in.LastTriggered, &out.LastTriggered
		*out = (*in).DeepCopy()
	}
	if in.LastCleared != nil {
		in, out := &in.LastCleared, &out.LastCleared
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
