apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/scada.io_plcdevices.yaml
- bases/scada.io_tags.yaml
- bases/scada.io_setpoints.yaml
- bases/scada.io_alarmpolicies.yaml
